<?php
$file = "app/Http/Controllers/ReportingController.php";
$c = file_get_contents($file);

// Fix fetchInventoryDemand
$c = preg_replace("/if \(\$isCartonMode\) \{\ns+(x[cartons\s]+=,*(int) floor\(\$qty / \$vPPB\);\ns+(x[loose\sm]+=,.*?;\ns+return .{#};\n}/", "if (\$isCartonMode) {\n                        \$ctnLbl = (\$vSizeMode === 'by_bandal') ? 'Bndl' : 'Ctn';\n                        \$cartons = (int) floor(\$qty / \$vPPB);\n                        \$loose   = (int) round(\$qty - (\$cartons * \$vPPB));\n                        return (\$loose > 0) ? \"{\$cartons} {\$ctnLbl} + {\$loose} Pcs\" : \"{\$cartons} {\$ctnLbl}\";\n                    }", $c);

$c = str_replace("if (\$isCartonMode) {\n                        \$cartons = round(\$qty / \$vPPB, 2);\n                        return \"{\$cartons} Ctn\";\n                    }", "if (\$isCartonMode) {\n                        \$ctnLbl = (\$vSizeMode === 'by_bandal') ? 'Bndl' : 'Ctn';\n                        \$cartons = round(\$qty / \$vPPB, 2);\n                        return \"{\$cartons} {\$ctnLbl}\";\n                    }", $c);

// Fix fetchItemStock (Variant loop)
$c = str_replace("if (\$isCartonMode) {\n                        \$cartons = (int) floor(\$balance / \$ppb);\n                        \$loose   = (int) round(\$balance - (\$cartons * \$ppb));\n                        \$formattedStock = (\$loose > 0) ? \"{\$cartons} Ctn + {\$loose} Pcs\" : \"{\$cartons} Ctn\";\n                        \$cartonDisplay = (\$loose > 0) ? \"{\$cartons} Ctn + {\$loose} Pcs <span class='text-muted small'>({\$ppb} pcs/ctn)</span>\" : \"{\$cartons} Ctn <span class='text-muted small'>({\$ppb} pcs/ctn)</span>\";\n                    }", "if (\$isCartonMode) {\n                        \$ctnLbl = (\$product->size_mode === 'by_bandal') ? 'Bndl' : 'Ctn';\n                        \$ctnFull = (\$product->size_mode === 'by_bandal') ? 'bndl' : 'ctn';\n                        \$cartons = (int) floor(\$balance / \$ppb);\n                        \$loose   = (int) round(\$balance - (\$cartons * \$pb));\n                        \$formattedStock = (\$loose > 0) ? \"{\$cartons} {\$ctnLbl} + {\$loose} Pcs\" : \"{\$cartons} {\$ctnLbl}\";\n                        \$cartonDisplay = (\$loose > 0) ? \"{\$cartons} {\$ctnLbl} + {\$loose} Pcs <span class='text-muted small'>({\$ppb} pcs/{\$ctnFull})</span>\" : \"{\$cartons} {\$ctnLbl} <span class='text-muted small'>({\$ppb} pcs/{\$ctnFull})</span>\";\n                    }", $c);

// Fix fetchItemStock (Base loop)
$c = str_replace("if (\$isCartonMode) {\n                    \$cartons = (int) floor(\$balance / \$ppb);\n                    \$loose   = (int) round(\$balance - (\$cartons * \$ppb));\n                    \$formattedStock = (\$loose > 0) ? \"{\$cartons} Ctn + {\$loose} Pcs\" : \"{\$cartons} Ctn\";\n                    \$cartonDisplay = (\$loose > 0) ? \"{\$cartons} Ctn + {\$loose} Pcs <span class='text-muted small'>({\$ppb} pcs/ctn)</span>\" : \"{\$cartons} Ctn <span class='text-muted small'>({\$ppb} pcs/ctn)</span>\";\n                }", "if (\$isCartonMode) {\n                    \$ctnLbl = (\$product->size_mode === 'by_bandal') ? 'Bndl' : 'Ctn';\n                    \$ctnFull = (\$product->size_mode === 'by_bandal') ? 'bndl' : 'ctn';\n                    \$cartons = (int) floor(\$balance / \$ppb);\n                    \$loose   = (int) round(\$balance - (\$cartons * \$ppb));\n                    \$formattedStock = (\$loose > 0) ? \"{\$cartons} {\$ctnLbl} + {\$loose} Pcs\" : \"{\$cartons} {\$ctnLbl}\";\n                    \$cartonDisplay = (\$loose > 0) ? \"{\$cartons} {\$ctnLbl} + {\$loose} Pcs <span class='text-muted small'>({\$ppb} pcs/{\$ctnFull})</span>\" : \"{\$cartons} {\$ctnLbl} <span class='text-muted small'>({\$ppb} pcs/{\$ctnFull})</span>\";\n                }", $c);

echo file_put_contents($file, $c) ? "Done" : "Failed";
